name: "Publish Docker Images"
description: "Publish updated Docker images to DockerHub"
inputs:
  dry_run:
    description: |
      Indicates the images should not actually be built and published, but prints what commands
      would be run if they were.
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - run: |
        function docker_tag_exists() {
            curl --silent -f -lSL https://index.docker.io/v1/repositories/$1/tags/$2 > /dev/null
        }

        python ${{ github.action_path }}/get_image_versions.py --output-file versions.tsv

        while IFS='\t' read -r repository version; do
          if docker_tag_exists ${repository} ${version}; then
            echo ${repository} ${version} "exists"
          else
            echo ${repository} ${version} "does not exist"
          fi
        done < versions.tsv
      shell: bash