name: "Publish Docker Images"
description: "Publish updated Docker images to DockerHub"
inputs:
  dry_run:
    description: |
      Indicates the images should not actually be built and published, but prints what commands
      would be run if they were.
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - run: |
        python ${{ github.action_path }}/get_image_versions.py --output-file versions.txt
        cat versions.txt
      shell: bash