name: "Publish Docker Images"
description: "Publish updated Docker images to DockerHub"
inputs:
  dry_run:
    description: |
      Indicates the images should not actually be built and published, but prints what commands
      would be run if they were.
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - run: |
        git remote set-url origin "https://${{ github.token }}@github.com/${{ github.repository }}"
        BASE_SHA=$(git rev-parse HEAD^1 2>&1) && exit_status=$? || exit_status=$?
        echo $BASE_SHA
      shell: bash